tabela = ('Corinthians', 'Palmeiras', 'Santos', 'Grêmio', 'Cruzeiro', 'Flamengo', 'Vasco', 'Chapecoense', 'Atlético', 'Botafogo', 'Atlético-PR', 'Bahia', 'São Paulo', 'Fluminense', 'Sport Recife', 'EC Vitória', 'Coritiba', 'Avaí', 'Ponte Preta', 'Atlético-GO')
print('-'*20)
print(f'Lista dos Times do Brasileirão: {tabela}')
print('-'*20)
print(f'Os cinco primeiros: {tabela[0:5]}')
print('-'*20)
print(f'Os Quatro últimos: {tabela[-4:]}')
print('-'*20)
print(f'Lista em Ordem Alfabética: {sorted(tabela)}')
print('-'*20)
print(f'O Chapecoense está na {tabela.index("Chapecoense")+1}ª posição')
